language: cpp

dist: bionic

addons:
  apt:
    packages:
      - cmake
      - flex
      - bison
      - libpcap-dev
      - libssl-dev
      - zlib1g-dev
      - libkrb5-dev
      - sqlite3
      - swig

install:
  - git clone --recursive https://github.com/zeek/zeek.git "$HOME"/zeek-src
  - pushd "$HOME"/zeek-src && ./configure --prefix="$HOME"/zeek && make && make install && popd
  - pip install --user zkg
  - PATH="$HOME/.local/bin:$HOME/zeek/bin:$PATH" zkg autoconfig

script:
  - PATH="$HOME/.local/bin:$HOME/zeek/bin:$PATH" zkg test .

after_failure:
  - cat "$HOME"/.zkg/logs/*-build.log
