name: Test

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y libpcap-dev

      - name: Install Zeek
        run: |
          git clone --recursive https://github.com/zeek/zeek.git "$HOME"/zeek-src
          pushd "$HOME"/zeek-src && ./configure --prefix="$HOME"/zeek && make && make install && popd
          pip3 install -U gitpython semantic-version

      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          PATH="$HOME/zeek/bin:$PATH" zkg test . || (
            for log in "$HOME"/zeek/var/lib/zkg/logs/*-build.log; do
              echo "$log" | sed -e "s#^$HOME/zeek/var/lib/zkg/##"
              cat "$log"
            done

            for log in "$HOME"/zeek/var/lib/zkg/testing/**/zkg.test_command.{stderr,stdout}; do
              echo "$log" | sed -e "s#^$HOME/zeek/var/lib/zkg/##"
              cat "$log"
            done

            exit 1
          )
